### ISSUE TITLE
nix setup failure on macos

### ISSUE THREAD

**Issue by junjihashimoto** [cachix/install-nix-action#10]
Sometimes, runing cachix/install-nix-action@v3 fails.
See following logs and screenshot.
Once the failure happens.  We can not recover it by retry.

https://github.com/hasktorch/hasktorch/pull/216/checks?check_run_id=291204004
![image](https://user-images.githubusercontent.com/2469618/68315252-d561c580-00fa-11ea-9150-34e4bcc49e44.png)

**Comment by domenkozar** [comment]
Watch #9 for progress, but I'm not sure this is even doable at the moment.

**Comment by tscholak** [comment]
nix on Catalina is not possible without mounting an additional volume for nix or moving all of nix to, say, `/opt/nix` because apple has chosen to make it impossible for anyone but them to write to `/`, see https://github.com/NixOS/nix/issues/2925.
Oh, I see you've already participated in the discussion, https://github.com/NixOS/nix/issues/2925#issuecomment-551036016 ;)

**Comment by tscholak** [comment]
maybe we could use https://nixos.wiki/wiki/Nix_Installation_Guide#nix-user-chroot

**Comment by tscholak** [comment]
are we really sure GitHub won't bring back 10.14? seems a bit weird, in a ci setting you'd want to test on many platforms and their versions

**Comment by tscholak** [comment]
people are starting to remove their macOS ci suites: https://github.com/arcnmx/nixexprs/commit/30aa6fc666eda301b9670d01391793c42c379323 :(

**Comment by arcnmx** [comment]
> people are starting to remove their macOS ci suites

I just don't have time to look into it right now and was tired of the failures.

> are we really sure GitHub won't bring back 10.14? seems a bit weird, in a ci setting you'd want to test on many platforms and their versions

They sent out an email stating they're deprecating/removing the other versions as soon as they've completed:

> Going forward, we will only support the `macos-latest` environment which will run Catalina (10.15). Once the migration to Catalina is complete, jobs using `macos-10.14` will no longer run.

So it seems pretty safe to say it won't be back.

**Comment by arcnmx** [comment]
Hah guess that wasn't such a safe assumption after all, treating this as an issue is much appreciated.

> We're considering re-adding support for Mojave or fully rolling back. How can we best help here?

Certainly bringing back Mojave would be the simplest interim solution, though it might be worth looking into whether disabling SIP would allow a workaround like #9 to work? Another approach might be for github to include changes to synthetic.conf in the image so that nix installs can have a symlink to the store, though iirc as discussed in https://github.com/NixOS/nix/issues/2925, symlinks aren't a proper/full solution and I'm not sure how well it works in practice.

**Comment by domenkozar** [comment]
> Is Catalina a full blocker for nix?

We're waiting on Apple and further investigation if that's the case. As mentioned disabling SIP should get us going.

> How can we best help here?

It would be easiest to have macos-10.14 around until catalina+nix is verified to work.

**Comment by thejoebourneidentity** [comment]
Hey everyone, it is risky at the moment for us to bring back Mojave to the overall stability of the macos virtual environment, we're continuing to monitor but the plan right now is to stick with 10.15. We're considering supporting Mojave side by side with Catalina but that likely will not happen until after we make Actions generally available next week. Big apologies, we're currently evaluating disabling SIP on the macos runners as an alternative. Hang tight!

**Comment by thejoebourneidentity** [comment]
It's also worth calling out [self-hosted runners](https://github.blog/2019-11-05-self-hosted-runners-for-github-actions-is-now-in-beta/) as an option to unblock your mac builds!

**Comment by domenkozar** [comment]
I guess the preferred solution for reducing your technical debt would be disabling SIP, so we can use Catalina. Once we figure out with Apple how to install Nix without the need to reboot and disabling SIP, we can revert that possibly.

If you have any good contact at Apple that would be appreciated.

**Comment by thejoebourneidentity** [comment]
We're also looking into this. I'll keep you up to date as we know more. The likely outcome is we'll disable SIP after Actions GA, but right now we're trying to keep things as stable as possible 🤞

**Comment by lilyball** [comment]
Any chance you could just pre-populate the VMs with an `/etc/synthetic.conf` that contains `nix`? That would allow us to install Nix without rebooting, and wouldn't have any downside that I can think of.

**Comment by thejoebourneidentity** [comment]
I will ask the team

**Comment by junjihashimoto** [comment]
@thejoebourneidentity 
Hi, I would like to use self hosted runners on public repository.
So I concern about security. Actually, I want to restrict hosted intance not to access servers of LAN.
(For example, hosted runner's network is connected to github-actions's one by VPN.)
Is it available?

**Comment by junjihashimoto** [comment]
@thejoebourneidentity 
Oh, github does not recommend it.
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories

**Comment by domenkozar** [comment]
We might have a solution at https://github.com/NixOS/nix/pull/3212 - I'll test it on github actions.

**Comment by junjihashimoto** [comment]
Thx!

**Comment by arcnmx** [comment]
> Any chance you could just pre-populate the VMs with an /etc/synthetic.conf that contains nix?

This appears to not be necessary because apfs.util can be used after editing the file to apply it without a reboot (as seen in the PR linked above).

> That would allow us to install Nix without rebooting, and wouldn't have any downside that I can think of.

There appear to be a number of downsides and limitations to using a symlink as a nix store path, I still believe disabling SIP is a more complete interim solution. Besides issues around a builder accidentally canonicalizing the symlink, I've already run into [couple](https://github.com/arcnmx/ci/commit/1eccf40a22865260fbd7fa7b137091c9656ef622) [subtle](https://github.com/arcnmx/ci/commit/519f9b2cc892ff7989194d003858727de7b87c5e) nix bugs attempting to do this.

**Comment by domenkozar** [comment]
I've tested and the fix works. Will wait on hotfix release of Nix.

**Comment by domenkozar** [comment]
Fixed in `install-nix-action-v5`! Thanks everyone, especially @thejoebourneidentity for quick support.

**Comment by arcnmx** [comment]
(given that this appears to be a workaround rather than a fix, I just want to note that I hope that doesn't encourage github to stop investigating into disabling SIP on Actions)

**Comment by thejoebourneidentity** [comment]
We're still looking into it, we're just holding back any changes right now since we just GA'd Actions at GitHub Universe today. We're still evaluating disabled SIP on our mac environment.
